[build]
command = "bash deploy.sh"   # Ejecuta el archivo deploy.sh
publish = "build/web"        # Publica la carpeta donde Flutter guarda los archivos web

[context.production.environment]
FLUTTER_CHANNEL = "stable"   # Usar la rama estable de Flutter
